# Generated by Django 4.0 on 2022-01-18 15:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_orgstructurepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('poster', models.ImageField(upload_to='uploads/img/gallery/%Y/%m', validators=[django.core.validators.validate_image_file_extension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Multimedia gallery',
                'verbose_name_plural': 'Multimedia galleries',
            },
        ),
        migrations.CreateModel(
            name='PhotoAlbumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/img/gallery/%Y/%m', validators=[django.core.validators.validate_image_file_extension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='webapp.photoalbum')),
            ],
            options={
                'verbose_name': 'Multimedia photo',
                'verbose_name_plural': 'Multimedia photos',
            },
        ),
    ]
