# Generated by Django 4.0 on 2022-01-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_photoalbum_photoalbumimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoalbum',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photoalbum',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photoalbum',
            name='title_zh_cn',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
